"""add reported usage watermark columns

Revision ID: 5876207a984b
Revises: 943fb9918228
Create Date: 2026-04-02 17:17:40.750055
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5876207a984b'
down_revision: Union[str, None] = '943fb9918228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('reported_trace_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_records', sa.Column('reported_trace_eval_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_records', sa.Column('reported_session_eval_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_records', 'reported_session_eval_count')
    op.drop_column('usage_records', 'reported_trace_eval_count')
    op.drop_column('usage_records', 'reported_trace_count')
    # ### end Alembic commands ###
