"""add status column to trace_scores

Revision ID: 7ccbb500ad9c
Revises: 26bcb17b08cd
Create Date: 2026-03-02 23:04:42.043496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccbb500ad9c'
down_revision: Union[str, None] = '26bcb17b08cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_scores', sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='score_status', native_enum=False, length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace_scores', 'status')
    # ### end Alembic commands ###
