"""add environment and release to traces

Revision ID: e6b8a7360199
Revises: e118961e5dcd
Create Date: 2026-02-25 13:51:03.111946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b8a7360199'
down_revision: Union[str, None] = 'e118961e5dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traces', sa.Column('environment', sa.String(length=255), nullable=True))
    op.add_column('traces', sa.Column('release', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'release')
    op.drop_column('traces', 'environment')
    # ### end Alembic commands ###
